[package]
name = "mesh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
snow = { workspace = true }
thiserror = { workspace = true }