global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Swarm Mesh Nodes - Dynamic service discovery via mesh-registry
  - job_name: 'mesh-node'
    http_sd_configs:
      - url: 'http://host.docker.internal:5000/prometheus/targets'
        refresh_interval: 10s
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http