global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Swarm Mesh Nodes
  - job_name: 'swarm-mesh-nodes'
    static_configs:
      - targets: 
          - 'host.docker.internal:8080'  # Node 1
          # Add more nodes as needed
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http 