global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Swarm Mesh Nodes - Dynamic service discovery via mesh-registry
  - job_name: 'mesh-node'
    http_sd_configs:
      - url: 'http://localhost:5000/prometheus/targets'
        refresh_interval: 5s
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http