apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    
  - name: Mesh-Registry
    type: marcusolsson-json-datasource
    access: proxy
    url: http://localhost:5000
    uid: mesh-registry
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET 